# Generated by Django 4.1 on 2022-11-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0012_remove_followers_followers_followers_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
