# Generated by Django 4.1 on 2022-11-11 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0013_alter_post_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='followers',
        ),
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='followers',
            name='followers',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
