# Generated by Django 4.1 on 2022-11-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0014_remove_followers_followers_alter_post_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default-propic', null=True, upload_to='profilepics'),
        ),
    ]
