# Generated by Django 4.1 on 2022-11-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0017_alter_myuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_pic',
            field=models.ImageField(default='profilepics/default-propic.png', upload_to='profilepics'),
        ),
    ]
