# Generated by Django 4.1 on 2022-11-13 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0018_alter_myuser_profile_pic'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followers',
            unique_together={('user', 'followers')},
        ),
    ]
